name: "pre-release"

on:
  push:
    branches:
      - "main"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          npm install
          npm run build
      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            Block/*
            Controller/*
            etc/*
            Helper/*
            images/*
            Logger/*
            Model/*
            Setup/*
            Ui/*
            view/*
            ViewModel/*
            composer.json
            LICENSE
            README.MD
            registration.php